import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ConditionalHeader from "@/components/ConditionalHeader";
import { ReactNode } from "react";
import ConditionalFooter from "@/components/ConditionalFooter";
import Transition from "./components/Transition";

export const metadata: Metadata = {
  title: "Thomas Profile",
  description: "Generated by create next app",
};

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <Transition>
      <html lang="en">
        <body className={`${inter.className} antialiased`} suppressHydrationWarning={true}>
          <ConditionalHeader />
          {children}
          <ConditionalFooter />
        </body>
      </html>
    </Transition>
  );
}
